import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { cn } from "../lib/utils";

export const metadata: Metadata = {
  title: {
    default: "Ta Web",
    template: "%s | Ta Web",
  },
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: {
    apple: "/icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          GeistSans.className,
          "bg-lightbg-200 min-h-screen flex flex-col"
        )}
      >
        {children}
      </body>
    </html>
  );
}
